### ISSUE TITLE
disks undefined local variable or method

### ISSUE THREAD

**Issue by JasonMcMahan** [dylanratcliffe/windows_disk_facts#12]
We received the following error after upgrading to version 2.0.0

error while resolving custom fact "disks": undefined local variable or method `disks_hashes_renamed' for #<Facter::Util::Resolution:0x00000004e90300>

The fix was to add 
line 9: disks_hashes_renamed = []

windows_disks.rb was the file noted.

**Comment by dylanratcliffe** [comment]
This was a bad merge. Should be fixed in v0.2.1
